-- ========================================
-- Schema Management
-- ========================================
--
-- Daily Event Insurance uses Drizzle ORM with Supabase PostgreSQL.
-- The authoritative schema is in: /lib/db/schema.ts
--
-- To manage the database:
--   npx drizzle-kit generate  # Generate migrations
--   npx drizzle-kit push      # Apply schema changes
--   npx drizzle-kit studio    # Visual database browser
--
-- Last updated: 2026-01-13
-- ========================================
