-- Stage 1: Production Readiness Migration
-- Generated by Simon-Schema Agent
-- Date: 2025-12-28
--
-- This migration addresses critical issues identified in the schema analysis:
-- 1. Missing foreign key indexes (causing full table scans)
-- 2. Missing unique constraints (allowing duplicate data)
-- 3. Missing CHECK constraints (allowing invalid data)
-- 4. New payments table (required for payment tracking)
-- 5. New claims table (required for insurance operations)

-- ============================================
-- SECTION 1: MISSING INDEXES ON FOREIGN KEYS
-- ============================================

-- Partners table - userId lookup on every API call
CREATE INDEX IF NOT EXISTS idx_partners_user_id ON partners(user_id);
CREATE INDEX IF NOT EXISTS idx_partners_approved_by ON partners(approved_by);

-- Partner products - partner lookup
CREATE INDEX IF NOT EXISTS idx_partner_products_partner_id ON partner_products(partner_id);

-- Monthly earnings - partner lookup
CREATE INDEX IF NOT EXISTS idx_monthly_earnings_partner_id ON monthly_earnings(partner_id);

-- Resource downloads - both FKs need indexes
CREATE INDEX IF NOT EXISTS idx_resource_downloads_partner_id ON resource_downloads(partner_id);
CREATE INDEX IF NOT EXISTS idx_resource_downloads_resource_id ON resource_downloads(resource_id);

-- Partner documents - partner lookup for webhook updates
CREATE INDEX IF NOT EXISTS idx_partner_documents_partner_id ON partner_documents(partner_id);

-- Webhook events - partner filtering
CREATE INDEX IF NOT EXISTS idx_webhook_events_partner_id ON webhook_events(partner_id);

-- Quotes - additional performance indexes
CREATE INDEX IF NOT EXISTS idx_quotes_customer_email ON quotes(customer_email) WHERE customer_email IS NOT NULL;

-- Policies - customer lookup for support
CREATE INDEX IF NOT EXISTS idx_policies_customer_email ON policies(customer_email);

-- ============================================
-- SECTION 2: COMPOSITE INDEXES FOR COMMON QUERIES
-- ============================================

-- Partner auth + status check (used on every authenticated request)
CREATE INDEX IF NOT EXISTS idx_partners_user_status ON partners(user_id, status);

-- Quote filtering by partner with status and date
CREATE INDEX IF NOT EXISTS idx_quotes_partner_status_created ON quotes(partner_id, status, created_at DESC);

-- Policy filtering by partner with status and date
CREATE INDEX IF NOT EXISTS idx_policies_partner_status_created ON policies(partner_id, status, created_at DESC);

-- Document lookup by partner and type
CREATE INDEX IF NOT EXISTS idx_partner_documents_partner_type ON partner_documents(partner_id, document_type);

-- ============================================
-- SECTION 3: PARTIAL INDEXES FOR COMMON FILTERS
-- ============================================

-- Active policies (most common query)
CREATE INDEX IF NOT EXISTS idx_policies_active ON policies(partner_id, event_date) WHERE status = 'active';

-- Pending quotes (quote processing queue)
CREATE INDEX IF NOT EXISTS idx_quotes_pending ON quotes(partner_id, expires_at) WHERE status = 'pending';

-- Unprocessed webhooks (retry queue)
CREATE INDEX IF NOT EXISTS idx_webhook_events_unprocessed ON webhook_events(created_at) WHERE processed = false;

-- ============================================
-- SECTION 4: UNIQUE CONSTRAINTS
-- ============================================

-- Prevent duplicate monthly earnings entries
ALTER TABLE monthly_earnings
  DROP CONSTRAINT IF EXISTS uq_monthly_earnings_partner_yearmonth;
ALTER TABLE monthly_earnings
  ADD CONSTRAINT uq_monthly_earnings_partner_yearmonth UNIQUE (partner_id, year_month);

-- Prevent duplicate document types per partner
ALTER TABLE partner_documents
  DROP CONSTRAINT IF EXISTS uq_partner_documents_partner_type;
ALTER TABLE partner_documents
  ADD CONSTRAINT uq_partner_documents_partner_type UNIQUE (partner_id, document_type);

-- ============================================
-- SECTION 5: CHECK CONSTRAINTS
-- ============================================

-- Quotes: Validate numeric fields
ALTER TABLE quotes DROP CONSTRAINT IF EXISTS chk_quotes_participants;
ALTER TABLE quotes ADD CONSTRAINT chk_quotes_participants CHECK (participants > 0 AND participants <= 10000);

ALTER TABLE quotes DROP CONSTRAINT IF EXISTS chk_quotes_premium;
ALTER TABLE quotes ADD CONSTRAINT chk_quotes_premium CHECK (premium > 0);

ALTER TABLE quotes DROP CONSTRAINT IF EXISTS chk_quotes_commission;
ALTER TABLE quotes ADD CONSTRAINT chk_quotes_commission CHECK (commission >= 0 AND commission <= premium);

-- Policies: Validate numeric fields and dates
ALTER TABLE policies DROP CONSTRAINT IF EXISTS chk_policies_participants;
ALTER TABLE policies ADD CONSTRAINT chk_policies_participants CHECK (participants > 0 AND participants <= 10000);

ALTER TABLE policies DROP CONSTRAINT IF EXISTS chk_policies_premium;
ALTER TABLE policies ADD CONSTRAINT chk_policies_premium CHECK (premium > 0);

ALTER TABLE policies DROP CONSTRAINT IF EXISTS chk_policies_commission;
ALTER TABLE policies ADD CONSTRAINT chk_policies_commission CHECK (commission >= 0 AND commission <= premium);

ALTER TABLE policies DROP CONSTRAINT IF EXISTS chk_policies_dates;
ALTER TABLE policies ADD CONSTRAINT chk_policies_dates CHECK (expiration_date >= effective_date);

-- Partner products: Validate price
ALTER TABLE partner_products DROP CONSTRAINT IF EXISTS chk_partner_products_price;
ALTER TABLE partner_products ADD CONSTRAINT chk_partner_products_price CHECK (customer_price > 0);

-- Monthly earnings: Validate counts
ALTER TABLE monthly_earnings DROP CONSTRAINT IF EXISTS chk_monthly_earnings_participants;
ALTER TABLE monthly_earnings ADD CONSTRAINT chk_monthly_earnings_participants CHECK (
  total_participants >= 0 AND
  opted_in_participants >= 0 AND
  opted_in_participants <= total_participants
);

ALTER TABLE monthly_earnings DROP CONSTRAINT IF EXISTS chk_monthly_earnings_commission;
ALTER TABLE monthly_earnings ADD CONSTRAINT chk_monthly_earnings_commission CHECK (partner_commission >= 0);

-- ============================================
-- SECTION 6: NEW PAYMENTS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_id UUID NOT NULL REFERENCES policies(id),
  partner_id UUID NOT NULL REFERENCES partners(id),

  -- Payment identification
  payment_number TEXT UNIQUE NOT NULL, -- PAY-YYYYMMDD-XXXXX

  -- Stripe integration
  stripe_payment_intent_id TEXT UNIQUE,
  stripe_charge_id TEXT,
  stripe_customer_id TEXT,

  -- Payment details
  amount DECIMAL(10, 2) NOT NULL CHECK (amount > 0),
  currency TEXT NOT NULL DEFAULT 'usd',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'succeeded', 'failed', 'refunded', 'partially_refunded', 'disputed')),
  payment_method TEXT, -- card, bank_transfer, etc.
  payment_method_details TEXT, -- JSON with last4, brand, etc.

  -- Refund tracking
  refund_amount DECIMAL(10, 2) DEFAULT 0 CHECK (refund_amount >= 0),
  refund_reason TEXT,
  refunded_at TIMESTAMP,

  -- Metadata
  receipt_url TEXT,
  failure_code TEXT,
  failure_message TEXT,
  metadata TEXT, -- JSON for additional data

  -- Timestamps
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Payment indexes
CREATE INDEX IF NOT EXISTS idx_payments_policy_id ON payments(policy_id);
CREATE INDEX IF NOT EXISTS idx_payments_partner_id ON payments(partner_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_stripe_intent ON payments(stripe_payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON payments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_partner_status ON payments(partner_id, status);

-- ============================================
-- SECTION 7: NEW CLAIMS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS claims (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  policy_id UUID NOT NULL REFERENCES policies(id),
  partner_id UUID NOT NULL REFERENCES partners(id),

  -- Claim identification
  claim_number TEXT UNIQUE NOT NULL, -- CLM-YYYYMMDD-XXXXX

  -- Claim details
  claim_type TEXT NOT NULL, -- injury, property_damage, liability, equipment_loss, cancellation
  incident_date TIMESTAMP NOT NULL,
  incident_location TEXT,
  incident_description TEXT NOT NULL,

  -- Claimant info
  claimant_name TEXT NOT NULL,
  claimant_email TEXT,
  claimant_phone TEXT,

  -- Financial
  claim_amount DECIMAL(10, 2) CHECK (claim_amount > 0),
  approved_amount DECIMAL(10, 2) CHECK (approved_amount >= 0),
  payout_amount DECIMAL(10, 2) DEFAULT 0 CHECK (payout_amount >= 0),
  deductible_amount DECIMAL(10, 2) DEFAULT 0 CHECK (deductible_amount >= 0),

  -- Status workflow: submitted -> under_review -> (approved|denied) -> (paid|closed)
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'under_review', 'additional_info_requested', 'approved', 'denied', 'paid', 'closed', 'disputed')),

  -- Review tracking
  assigned_to TEXT, -- Adjuster name/id
  review_notes TEXT,
  denial_reason TEXT,

  -- Timestamps
  submitted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMP,
  approved_at TIMESTAMP,
  denied_at TIMESTAMP,
  paid_at TIMESTAMP,
  closed_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Claims indexes
CREATE INDEX IF NOT EXISTS idx_claims_policy_id ON claims(policy_id);
CREATE INDEX IF NOT EXISTS idx_claims_partner_id ON claims(partner_id);
CREATE INDEX IF NOT EXISTS idx_claims_status ON claims(status);
CREATE INDEX IF NOT EXISTS idx_claims_incident_date ON claims(incident_date);
CREATE INDEX IF NOT EXISTS idx_claims_created_at ON claims(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_claims_partner_status ON claims(partner_id, status);

-- Partial index for open claims
CREATE INDEX IF NOT EXISTS idx_claims_open ON claims(partner_id, created_at)
  WHERE status NOT IN ('paid', 'closed', 'denied');

-- ============================================
-- SECTION 8: CLAIM DOCUMENTS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS claim_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  claim_id UUID NOT NULL REFERENCES claims(id) ON DELETE CASCADE,

  -- Document details
  document_type TEXT NOT NULL, -- photo, receipt, medical_report, police_report, witness_statement, other
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_size INTEGER, -- bytes
  mime_type TEXT,

  -- Metadata
  description TEXT,
  uploaded_by TEXT, -- claimant, partner, adjuster

  -- Timestamps
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Claim documents indexes
CREATE INDEX IF NOT EXISTS idx_claim_documents_claim_id ON claim_documents(claim_id);
CREATE INDEX IF NOT EXISTS idx_claim_documents_type ON claim_documents(document_type);

-- ============================================
-- SECTION 9: ADD PRICING METADATA COLUMNS
-- ============================================

-- Add columns to quotes for better analytics
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS duration DECIMAL(4, 1); -- hours
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS risk_multiplier DECIMAL(5, 3);
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS commission_tier INTEGER;

-- Add columns to policies (mirror quotes)
ALTER TABLE policies ADD COLUMN IF NOT EXISTS duration DECIMAL(4, 1);
ALTER TABLE policies ADD COLUMN IF NOT EXISTS location TEXT;
ALTER TABLE policies ADD COLUMN IF NOT EXISTS risk_multiplier DECIMAL(5, 3);
ALTER TABLE policies ADD COLUMN IF NOT EXISTS commission_tier INTEGER;

-- ============================================
-- SECTION 10: AUDIT TRIGGER FUNCTION
-- ============================================

-- Create updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply trigger to tables with updated_at
DROP TRIGGER IF EXISTS update_quotes_updated_at ON quotes;
CREATE TRIGGER update_quotes_updated_at
  BEFORE UPDATE ON quotes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_policies_updated_at ON policies;
CREATE TRIGGER update_policies_updated_at
  BEFORE UPDATE ON policies
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_partners_updated_at ON partners;
CREATE TRIGGER update_partners_updated_at
  BEFORE UPDATE ON partners
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_partner_documents_updated_at ON partner_documents;
CREATE TRIGGER update_partner_documents_updated_at
  BEFORE UPDATE ON partner_documents
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_payments_updated_at ON payments;
CREATE TRIGGER update_payments_updated_at
  BEFORE UPDATE ON payments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_claims_updated_at ON claims;
CREATE TRIGGER update_claims_updated_at
  BEFORE UPDATE ON claims
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- VERIFICATION QUERIES (run after migration)
-- ============================================

-- Uncomment to verify migration success:
-- SELECT indexname FROM pg_indexes WHERE tablename IN ('partners', 'quotes', 'policies', 'payments', 'claims');
-- SELECT conname FROM pg_constraint WHERE conrelid IN ('quotes'::regclass, 'policies'::regclass);
-- SELECT table_name FROM information_schema.tables WHERE table_name IN ('payments', 'claims', 'claim_documents');
